version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"      # Map port 8080 in the container to 3000 on the host
      - "11434:8080"     # Map port 8080 in the container to 11434 on the host
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "memer.local:host-gateway"  # Map memer.local to the host gateway
    volumes:
      - open-webui:/app/backend/data
    restart: always

volumes:
  open-webui:
